from __future__ import annotations
import typing
from . import tests
__all__: list[str] = ['get_subtests', 'get_test', 'get_tests', 'run_test', 'tests']
def get_subtests(arg0: str) -> list:
    ...
def get_test(arg0: str) -> typing.Any:
    ...
def get_tests() -> list:
    ...
def run_test(arg0: str) -> None:
    ...
